---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy nginx configuration for gateway
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
